//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IBook 
{
	string Name { get;set; }

	string Author { get;set; }

	int PublicationDate { get;set; }

	int Raiting { get;set; }

	string Path { get;set; }

	object _Id { get;set; }

}

